---
- name: Deploy refresh file
  ansible.builtin.template:
    src: refresh.txt.j2
    dest: "{{ config_dir }}/refresh.txt"
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Deploy URL files
  ansible.builtin.template:
    src: url.txt.j2
    dest: "{{ config_dir }}/url.txt"
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Deploy wifi-watchdog config file
  ansible.builtin.template:
    src: wifi-watchdog.conf.j2
    dest: "{{ config_dir }}/wifi-watchdog.conf"
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Deploy kiosk script file
  ansible.builtin.template:
    src: kiosk.sh.j2
    dest: "{{ scripts_dir }}/kiosk.sh"
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Deploy Wifi-Watchdog Service
  ansible.builtin.template:
    src: wifi-watchdog.service.j2
    dest: "/etc/systemd/system/wifi-watchdog.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable and start wifi-watchdog service
  become: true
  ansible.builtin.systemd:
    name: wifi-watchdog.service
    daemon_reload: true
    enabled: true
    state: started

- name: Install Kiosk Autostart
  ansible.builtin.template:
    src: kiosk.desktop.j2
    dest: "{{ home_dir }}/.config/autostart/{{ kiosk_name }}_kiosk.desktop"
    owner: "{{ ansible_user }}"
    mode: "0755"