- name: Set repo name from ansible_user
  ansible.builtin.set_fact:
    repo_name: "{{ ansible_user }}"

- name: Define node home
  ansible.builtin.set_fact:
    node_home: "/home/{{ ansible_user }}"

- name: Clone repo matching user
  ansible.builtin.git:
    repo: "https://github.com/OnyxJeff/{{ repo_name }}.git"
    dest: "{{ node_home }}/{{ repo_name }}"
    update: yes
  become: true
  become_user: "{{ ansible_user }}"