- name: Install kiosk dependencies
  apt:
    name:
      - chromium-browser
      - unclutter
      - x11-xserver-utils
    state: present

- name: Install autostart config
  template:
    src: autostart.desktop.j2
    dest: "/home/{{ node_user }}/.config/autostart/kiosk.desktop"