---
- name: Use script install on Raspberry Pi OS or unknown Debian variants
  ansible.builtin.include_tasks: install_script.yml
  when:
    - ansible_distribution == "Raspbian"
      or ansible_distribution == "Debian"
      and ansible_distribution_release in ["bookworm", "bullseye", "trixie"]

- name: Use APT repo install on Ubuntu / Proxmox / modern Debian servers
  ansible.builtin.include_tasks: install_apt_repo.yml
  when:
    - ansible_distribution == "Ubuntu"
      or (ansible_distribution == "Debian"
          and ansible_distribution != "Raspbian")