---
- name: Detect if Docker already installed
  ansible.builtin.command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Install Docker if missing
  ansible.builtin.include_tasks: install.yml
  when: docker_check.rc != 0

- name: Ensure docker users are in docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Force Raspberry Pi reboot after docker setup
  ansible.builtin.reboot:
    msg: "Forcing reboot after docker user setup"
    reboot_timeout: 900
    pre_reboot_delay: 5
    post_reboot_delay: 30