---
- name: Detect if Docker already installed
  ansible.builtin.command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Install Docker if missing
  ansible.builtin.include_tasks: install.yml
  when: docker_check.rc != 0

- name: Ensure docker users are in docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"