- name: Base system for all PotentPis
  hosts: raspberries
  become: true

  roles:
    - pi_base

    - role: docker
      when: enable_docker | default(false)

    - role: dockprom
      when: enable_dockprom | default(false)

    - role: display_oled
      when: enable_display_oled | default(false)

    - role: display_kiosk
      when: enable_display_kiosk | default(false)

    - role: unifi
      when: enable_unifi | default(false)

    - role: pihole
      when: enable_pihole | default(false)

    - role: transmission
      when: enable_transmission | default(false)