- name: Base system for all PotentPis
  hosts: potentpi
  become: yes
  roles:
    - base
    - docker
    - os_update
    - containers

- name: DNS Node (Pi-hole)
  hosts: dns
  become: yes
  roles:
    - pihole

- name: UniFi Node
  hosts: unifi
  become: yes
  roles:
    - unifi

- name: Transmission Node
  hosts: torrent
  become: yes
  roles:
    - transmission

- name: Control Node
  hosts: control
  become: yes
  roles:
    - ansible_control

- name: DashPi Nodes
  hosts: dashpi
  become: yes
  roles:
    - kiosk

- name: DashPi NOC Node
  hosts: dashpi_noc
  become: yes
  roles:
    - kiosk