enable_pi_base: false
enable_docker: false
enable_dockprom: false
enable_display_oled: false
enable_display_kiosk: false
enable_unifi: false
enable_pihole: false
enable_transmission: false
pihole_backup_base: "{{ playbook_dir }}/../inventory/files/pihole"