---
- import_tasks: prereqs.yml
- import_tasks: install.yml
- import_tasks: restore.yml
- import_tasks: validate.yml
- import_tasks: exporter.yml
  when: inventory_hostname == "svr-odin"
- import_tasks: nebula.yml
  when: inventory_hostname == "svr-odin"

- name: Rebuild gravity
  command: sudo pihole -g